import Head from "next/head";
import React from "react";
import Navbar from "../Navbar";
import styles from './../../styles/Home.module.css';

interface IMainLayout {
	children:React.ReactNode
}

const MainLayout = ({children}:IMainLayout) => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<main className={styles.main}>
				{children}
			</main>
		</div>
	);
}

export default MainLayout;